### ISSUE TITLE
What is exactly the shopware playground url

### ISSUE THREAD

**Issue by aloiki** [shopwareLabs/pg-experiment-one-page-shop#1]
Hello,

I am new to shopware and also to the playground and I like to experience this experiment locally. Already logged into my SW Playground Account and generated the API Key. Now I am a little bit confused about what you mean by shopware playground url.

**Comment by mitelg** [comment]
this should be the URL of your playground instance. something like this: `https://<your-shopware-id>-1234.pg.shopware.com/`

**Comment by mitelg** [comment]
can we close this issue?
